image: registry.smtx.io/cloudtower/node:16-ubuntu-focal-pnpm2

stages:
  - turbo
turbo-run:
  stage: turbo
  image:
    - registry.smtx.io/cloudtower/node:16-ubuntu-focal-pnpm2,
    - registry.smtx.io/cloudtower/node:16-alpine,
  script:
    - pnpm install --frozen-lockfile
    - pnpm start
