image: registry.smtx.io/cloudtower/node:16-ubuntu-focal

stages:
  - turbo
turbo-run:
  stage: turbo
  script:
    - yarn install
    - yarn test

turbo-run-alpine:
  stage: turbo
  image: registry.smtx.io/cloudtower/node:16-alpine
  script:
    - apk add --no-cache libc6-compat
    - yarn install
    - yarn test